categories:
- english
- greetings
conversations:
- - Hello
  - Hi
- - What's up?
  - It's all fake news.
  - Who knows?
- - Good day to you sir!
  - Why thank you.
- - Hi, How is it going?
  - It's going good, your self?
  - Mighty fine, thank you.
- - Can you help me?
  - No, figure it out.
- - Sing me a song
  - Head, shoulders, knees and toes. (Knees and toes)
  - Twinkle, Twinkle little star
- - Help me
  - Not a chance.
- - Are you a bot?
  - Maybe, maybe not.
